### ISSUE TITLE
关于资源引用的一个问题

### ISSUE THREAD

**Issue by asan855** [bunnyblue/OpenAtlas#161]
我的插件中需要调用alipay支付，流程是这样的：阿里的jar包中包含一个支付的Activity，这个Activity加载布局的方式是这样的，Context.getResources().getIdentifier(name, type, pkgName);这样的话加载布局会去找
com.host.pkg.R$layout里面的布局，显然是找不到的，然后就报错了，这个有解决的办法吗

**Comment by bunnyblue** [comment]
@asan855 	直接的话可能不行，这个框架与代理实现的不一样，你所添加在资源得整个APP中唯一的，当然你的name可能相同，这边一定要小心
```
		
			drawable = Class.forName("com.openatlas.qrcode" + ".R$drawable");

你给我的demo是下面的代码，正确的用法用该是上面，paramContext这个获取报名，因为在统一进程，没法确定的是那一个，所以建议你在里面指定

                drawable = Class.forName(paramContext.getPackageName()+ ".R$drawable");


```

还有一个方案，如果这几个资源不多的话你可以把这几个资源的id使用public.xml这种形式固定下来，在java里面直接id用你public里面所定义的。

对于支付宝这种暂时没有好的解决方案，对组件或者程序使用getPackageName，应该获取的是真是的报名，而不应该是组件的，支付宝里面，用的是Application，这个暂时不好解决，虽然可以用堆栈调用顺序查看，但是这个降级性能，这种建议放在宿主里面，或者修改jar，把查找资源那块修正下。
我记得银联的jar可以设置包名，支付宝这点做的不太好

**Comment by asan855** [comment]
感谢，暂时放到宿主了。
不过按我同事的说法也能理解通，假如把宿主和atlas理解成Android系统的话，每个apk就是安装在系统里面的应用，这个时候原则上获取包名应该是该apk的包名，而不应该是宿主的

**Comment by bunnyblue** [comment]
你的理解毫无悬念是对的，但是android每个进程都是独立的，OpenAtlas所有的组件都依托于宿主，这是与Android系统的差异.他们属于一个，如果这边理解有误的话看下，wiki里面有关于整个OpenAtlas资源分布结构图，基本就这么回事，感觉这个问题修复的概率比较低
