### ISSUE TITLE
Activity必须在宿主的manifest注册？那这样动态部署有什么意义？

### ISSUE THREAD

**Issue by lihehub** [bunnyblue/OpenAtlas#163]
对于QA中的问题的回答存在疑惑，作者没有回答根本问题。启动真正的activity，而不能动态部署，就无法动态升级、扩展功能，难道该框架只适用于开发期，对于应用上线的运维期无能为力吗？如果这样的话，就没必要进行插件化，做好程序的模块化、组件化就可以了。

**Comment by bunnyblue** [comment]
README说的很清楚了必须注册。
