### ISSUE TITLE
5.0的支持问题

### ISSUE THREAD

**Issue by xk009** [bunnyblue/OpenAtlas#164]
为什么5.0不能支持，是哪方面的问题。

**Comment by bunnyblue** [comment]
支持啊，怎么不支持

**Comment by xk009** [comment]
5.0 下。在versionName加上0x 之后，theme的属性找不到，导致我明明在theme里设置了NoActionBar的属性，还显示了bar。 其他系统就可以。 把versionName的0x去掉，5.0显示正常。但是这样就不能资源分区了。

**Comment by bunnyblue** [comment]
@xk009 你在宿主的manifest配置了吗？

**Comment by xk009** [comment]
现在是单独运行 有0xPackageId的 插件apk都会这样. 限于5.0的系统。

**Comment by xk009** [comment]
如果 设置成0x7f 的话，就可以，怀疑5.0那边的资源分区后， 查找机制有点问题。

**Comment by bunnyblue** [comment]
android:theme="@android:style/Theme.DeviceDefault.NoActionBar" 我在ext项目下的 qrcode  测试，没啥问题啊

**Comment by xk009** [comment]
<style name="AppTheme" parent="Theme.AppCompat.NoActionBar">  我是设置 这个的。

**Comment by xk009** [comment]
style name="AppTheme" parent="Theme.AppCompat.NoActionBar"

**Comment by xk009** [comment]
用你 那个主题 在5.0上 也是一样的。

**Comment by xk009** [comment]
我的qq是 19018972，加我下好友吧。谢谢了。

**Comment by bunnyblue** [comment]
暂时无法浮现问题，你AppCompat这个在插件里面编译的吗？你用ext项目下的二维码那个试下呗，测试了下没问题，不清楚的supportv7怎么处理，应该只在宿主里面吧

**Comment by xk009** [comment]
你是用5.0的系统试的吗。我用了ext的二维码，结果是其他系统都是没有 ActionBar。 5.0系统还是有ActionBar。 我的主题设置是 Theme.DeviceDefault.NoActionBar

**Comment by bunnyblue** [comment]
这个真见鬼了，我试了Theme.DeviceDefault.NoActionBar这个没问题啊，标题也没有了，暂不确定什么情况，我用的5.0的模拟器

**Comment by xk009** [comment]
style name="AppBaseTheme" parent="android:style/Theme.DeviceDefault.NoActionBar"  用 AppBaseTheme 应用的主题。而不是直接用Theme.DeviceDefault.NoActionBar. 我试过了，如果直接用 android:style/Theme.DeviceDefault.NoActionBar 在清单文件设置applactoin的主题的话，没问题的。用AppBaseThme 就有问题。

**Comment by bunnyblue** [comment]
07-17 15:39:36.641    1495-1495/? E/ResourceType﹕ Failed resolving bag parent id 0x6c080000
07-17 15:39:36.642    1495-1495/? W/ResourceType﹕ Attempt to retrieve bag 0x6c080001 which is invalid or in a cycle. 你先直接用吧，这个还需要分析下什么情况

**Comment by xk009** [comment]
好的。时刻关注楼主。

**Comment by bunnyblue** [comment]
```
  // First see if we've already computed this bag...

3819    if (grp->bags) {
3820        bag_set** typeSet = grp->bags->get(t);
3821        if (typeSet) {
3822            bag_set* set = typeSet[e];
3823            if (set) {
3824                if (set != (bag_set*)0xFFFFFFFF) {
3825                    if (outTypeSpecFlags != NULL) {
3826                        *outTypeSpecFlags = set->typeSpecFlags;
3827                    }
3828                    *outBag = (bag_entry*)(set+1);
3829                    //ALOGI("Found existing bag for: %p\n", (void*)resID);
3830                    return set->numAttrs;
3831                }
3832                ALOGW("Attempt to retrieve bag 0x%08x which is invalid or in a cycle.",
3833                     resID);
3834                return BAD_INDEX;
3835            }
3836        }
3837    }

```


建议采取别方案，等有时间看下ResourceTypes，这部分代码基本这样子，估计比较悬，如果跟着一部分代码有关的花就暂时无法解决，这部分在新版本的系统中

**Comment by bunnyblue** [comment]
@xk009   查了下，各种插件化的主题或多或少得有类似的问题，建议把style放到宿主里面，注册activity的时候还是用宿主的style

**Comment by bunnyblue** [comment]
测试了下，这边属于系统问题，在ResourceTypes.cpp，写死了，如果是package-id 为0x7f的话返回NO_ERROR，这边写死了，估计暂时无解

**Comment by bunnyblue** [comment]
status is here https://code.google.com/p/android/issues/detail?id=180542

**Comment by xk009** [comment]
您好，你们的插件没用support的主题吗。我想，我们现在 只能用自定义的TitleBar了。

**Comment by bunnyblue** [comment]
无力支持，我觉得我上面说的够清楚了吧，难道你每个插件都有一个support吗
