### ISSUE TITLE
插件可以不放在主工程的libs/armeabi目錄下麼

### ISSUE THREAD

**Issue by ymcao** [bunnyblue/OpenAtlas#168]
插件可以不放在主工程的libs/armeabi目錄下麼？

**Comment by bunnyblue** [comment]
当然可以了，你可以放任何地方，但是你可能需要修改代码，如果你在插件放在libs下的话可以使用AtlasConfig.PRELOAD_DIR设置
```

 public static String PRELOAD_DIR = "armeabi";
```
默认值值这样，不然的话就修改代码了
放在libs主要为了加快启动速度，你有其余的地方也可以改，搜下PRELOAD_DIR这个就好了，暂时没提供其余的搜索位置

**Comment by xh2009cn** [comment]
你好，我发现插件apk的Application的onCreate方法，每启动一个Activity就会执行一次；而且有的插件启动会报错：Caused by: java.lang.ClassCastException: com.openatlas.launcher.BootApp cannot be cast to com.xxx.MyApplication，不知道是不是我哪里搞错了

**Comment by bunnyblue** [comment]
@xh2009cn   Caused by: java.lang.ClassCastException: com.openatlas.launcher.BootApp cannot be cast to com.xxx.MyApplication 这个你代码写的有问题吧，你不用把context转为MyApplication

**Comment by bunnyblue** [comment]
if any question,reopen
