### ISSUE TITLE
插件apk的Application的onCreate方法，每启动一个Activity就会执行一次，不知是否可以避免？

### ISSUE THREAD

**Issue by xh2009cn** [bunnyblue/OpenAtlas#171]
你好，我发现插件apk的Application的onCreate方法，每启动一个Activity就会执行一次；而且有的插件启动会报错：Caused by: java.lang.ClassCastException: com.openatlas.launcher.BootApp cannot be cast to com.xxx.MyApplication，不知道是不是我哪里搞错了

**Comment by bunnyblue** [comment]
更新状态：正在解决
