### ISSUE TITLE
LexFile不存在？

### ISSUE THREAD

**Issue by fengcunhan** [bunnyblue/OpenAtlas#181]
OpenAtlasHacks.java 中 LexFile = Hack.into("dalvik.system.LexFile");  但是网上没有任何的关于class dalvik.system.LexFile的信息，是不是 dalvik.system.DexFile ？

**Comment by bunnyblue** [comment]
@fengcunhan  No Lex is YunOS  file format you can ref at http://www.zhihu.com/question/20478639 ,if no  problem,you can close  it 😄

**Comment by fengcunhan** [comment]
OK,I know it.
