### ISSUE TITLE
能否在宿主中反射调用插件中的Fragment？

### ISSUE THREAD

**Issue by lizhangqu** [bunnyblue/OpenAtlas#188]
如题，如果直接用**Class.forName(clazz).newInstance();**，会报**java.lang.ClassNotFoundException**，如果可以调，应该如何调用？

**Comment by bunnyblue** [comment]
找这个类bundle的classloader

**Comment by lizhangqu** [comment]
感谢，解决了，找对应的ClassLoader就OK了
```
ClassLoader bundleClassLoader = Atlas.getInstance().getBundleClassLoader(bundlepkgName);
```
