### ISSUE TITLE
FrameworkLifecycleHandler bad code

### ISSUE THREAD

**Issue by myqhit** [bunnyblue/OpenAtlas#195]
public void frameworkEvent(FrameworkEvent frameworkEvent) {
        switch (frameworkEvent.getType()) {
            case FrameworkEvent.STARTING:
                starting();
                break;
            case FrameworkEvent.STARTED:
                started();
                break;
            default:
        }
    }
楼主的case中没有break，导致STARTING事件来时，同时会执行STARTED事件，不知道理解的正确不

**Comment by bunnyblue** [comment]
yes,.problem .fixed
