### ISSUE TITLE
Is the bundle app running in the same Process?

### ISSUE THREAD

**Issue by xk009** [bunnyblue/OpenAtlas#196]
Using Otto, I subscribe some event in the Activity which is in bundle app 。 Then I send Event in Host App。Bundle app can't received the event。I want to ask Is the bundle app running in the same Process?

**Comment by bunnyblue** [comment]
right,all bundles run in host process

**Comment by xk009** [comment]
thank you! you can close the issue.

**Comment by bunnyblue** [comment]
problem solved？

**Comment by xk009** [comment]
我先自己研究下看，是不是因为不同的classloader 导致 Bus 不是同一个。或者你能给个 方案，能不同bundle之间通信，但是不能耦合，就是不能有直接代码引用。

**Comment by bunnyblue** [comment]
有时间看下，最近比较忙

**Comment by xk009** [comment]
好的，谢啦。

**Comment by bunnyblue** [comment]
@xk009  基本解决，两个bundle通信，用的otto，一个bundle在里面发送通知 OpenAtlasm 使用 v1.0.0-rc分支测试，OpenAtlasExtension 使用master分支，或者1.0.0分支

启动app后点击菜单 DService启动服务，这个服务不500毫秒发一次广播，然后到Appcenter那个bundle启动Internal那个activity 应该是ok的，等有时间我把home里面的放到宿主里面
